version: '3'
services:
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  db:
    image: mysql:5.7
    restart: always
    container_name: poc-auth-db
    environment:
      MYSQL_DATABASE: 'poc-auth-db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

volumes:
  my-db:

networks:
  app-network:
    driver: bridge