http://localhost:3000/api/signUp?name=Camila

### Get All users
GET http://localhost:3000/api/signUp/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNmQ4NTQzLWExY2EtNDY2ZC1hNjVlLTYwMGI3ZmRhOTcxNSIsImlhdCI6MTY4MzAzNjE4OCwiZXhwIjoxNjgzMDU0MTg4fQ.FpZFEyrsp1g-6Qach5bKJIvMr0ofXoJqBNiHhac_MFw

### Send POST request with json body
POST http://localhost:3000/api/auth/send-recover-email
Content-Type: application/json

{
  "email": "mila3@mail.com"
}

### Create a new user
POST http://localhost:3000/api/signUp/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNmQ4NTQzLWExY2EtNDY2ZC1hNjVlLTYwMGI3ZmRhOTcxNSIsImlhdCI6MTY4MzAzNjE4OCwiZXhwIjoxNjgzMDU0MTg4fQ.FpZFEyrsp1g-6Qach5bKJIvMr0ofXoJqBNiHhac_MFw

{
  "name": "Milene Silva",
  "email": "milene@mail.com",
  "password": "Milene.123",
  "passwordConfirmation": "Milene.123"
}

### Create a new admin
POST http://localhost:3000/api/signUp/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNmQ4NTQzLWExY2EtNDY2ZC1hNjVlLTYwMGI3ZmRhOTcxNSIsImlhdCI6MTY4MzAzNjE4OCwiZXhwIjoxNjgzMDU0MTg4fQ.FpZFEyrsp1g-6Qach5bKJIvMr0ofXoJqBNiHhac_MFw

{
  "name": "Teste",
  "email": "teste@mail.com",
  "password": "Teste.123",
  "passwordConfirmation": "Teste.123"
}

### SignIn
POST http://localhost:3000/api/auth/signIn
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "Admin.123"
}

### Me
GET http://localhost:3000/api/auth/me
Content-Type: application/json
{


